# Generated by Django 2.0.1 on 2018-02-20 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20180220_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.PositiveIntegerField(null=True)),
                ('course_id', models.PositiveIntegerField(null=True)),
                ('passed', models.IntegerField(default=0)),
            ],
        ),
    ]
