# Generated by Django 2.0.1 on 2018-02-05 16:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import olymps.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Olymp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('draft', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=olymps.models.upload_location, width_field='width_field')),
                ('height_field', models.IntegerField(default=0)),
                ('width_field', models.IntegerField(default=0)),
                ('publish', models.DateField()),
                ('start_time', models.DateField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['start_time', '-timestamp'],
            },
        ),
    ]
