# Generated by Django 2.0.1 on 2018-02-19 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0003_remove_lecture_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='level',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
