# Generated by Django 2.0.1 on 2018-02-20 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0005_auto_20180220_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passlecture',
            name='passed',
            field=models.IntegerField(default=0),
        ),
    ]
