# Generated by Django 2.0.1 on 2018-03-04 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0003_functions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='functions',
            name='list',
        ),
        migrations.AddField(
            model_name='functions',
            name='name',
            field=models.TextField(default='de'),
        ),
    ]
