# Generated by Django 2.0.1 on 2018-03-04 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0004_auto_20180304_2339'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Functions',
            new_name='Function',
        ),
    ]
