# Generated by Django 2.0.1 on 2018-03-04 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0005_auto_20180304_2341'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Function',
            new_name='Lemma',
        ),
    ]
